=== jorge2106/Lab5_Cinema/web/xmlFile/FunctionDTD.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/FunctionDTD.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE functions SYSTEM "FunctionDTD.dtd">

    <functions>
    ...
    </functions>
-->

<!--- Put your DTDDoc comment here. -->
<!ELEMENT functions (function)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT function (date|hour|rowCant|columnCant|seats)*>
<!ATTLIST function
    movieId CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT date (day|month|year)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT day (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT month (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT year (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT hour (hours|min)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT hours (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT min (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT rowCant (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT columnCant (#PCDATA)>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT seats (seat)*>

<!--- Put your DTDDoc comment here. -->
<!ELEMENT seat (state)*>
<!ATTLIST seat
    id CDATA #IMPLIED
  >

<!--- Put your DTDDoc comment here. -->
<!ELEMENT state (#PCDATA)>

=== jorge2106/Lab5_Cinema/web/xmlFile/Function.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<!DOCTYPE functions SYSTEM "FunctionDTD.dtd">

<functions>
    <function id="76215">
        <date>
            <day>11</day>
            <month>06</month>
            <year>2016</year>
        </date>
        <hour>
            <hours>3</hours>
            <min>10</min>
        </hour>
        <rowCant>4</rowCant>
        <columnCant>5</columnCant>
        <seats>
            <seat id="A1">
                <state>0</state>
            </seat>
            <seat id="A2">
                <state>0</state>
            </seat>
            <seat id="A3">
                <state>0</state>
            </seat>
            <seat id="A4">
                <state>0</state>
            </seat>
            <seat id="B1">
                <state>0</state>
            </seat>
            <seat id="B2">
                <state>0</state>
            </seat>
            <seat id="B3">
                <state>0</state>
            </seat>
            <seat id="B3">
                <state>0</state>
            </seat>
            <seat id="B4">
                <state>0</state>
            </seat>
            <seat id="C1">
                <state>0</state>
            </seat>
            <seat id="C2">
                <state>0</state>
            </seat>
            <seat id="C3">
                <state>0</state>
            </seat>
            <seat id="C4">
                <state>0</state>
            </seat>
            <seat id="D1">
                <state>0</state>
            </seat>
            <seat id="D2">
                <state>0</state>
            </seat>
            <seat id="D3">
                <state>0</state>
            </seat>
            <seat id="D4">
                <state>0</state>
            </seat>
            <seat id="E1">
                <state>0</state>
            </seat>
            <seat id="E2">
                <state>0</state>
            </seat>
            <seat id="E3">
                <state>0</state>
            </seat>
            <seat id="E4">
                <state>0</state>
            </seat>
        </seats>
    </function>
     <function id="76215">
        <date>
            <day>12</day>
            <month>06</month>
            <year>2016</year>
        </date>
        <hour>
            <hours>1</hours>
            <min>30</min>
        </hour>
        <rowCant>4</rowCant>
        <columnCant>5</columnCant>
        <seats>
            <seat id="A1">
                <state>0</state>
            </seat>
            <seat id="A2">
                <state>0</state>
            </seat>
            <seat id="A3">
                <state>0</state>
            </seat>
            <seat id="A4">
                <state>0</state>
            </seat>
            <seat id="B1">
                <state>0</state>
            </seat>
            <seat id="B2">
                <state>0</state>
            </seat>
            <seat id="B3">
                <state>0</state>
            </seat>
            <seat id="B3">
                <state>0</state>
            </seat>
            <seat id="B4">
                <state>0</state>
            </seat>
            <seat id="C1">
                <state>0</state>
            </seat>
            <seat id="C2">
                <state>0</state>
            </seat>
            <seat id="C3">
                <state>0</state>
            </seat>
            <seat id="C4">
                <state>0</state>
            </seat>
            <seat id="D1">
                <state>0</state>
            </seat>
            <seat id="D2">
                <state>0</state>
            </seat>
            <seat id="D3">
                <state>0</state>
            </seat>
            <seat id="D4">
                <state>0</state>
            </seat>
            <seat id="E1">
                <state>0</state>
            </seat>
            <seat id="E2">
                <state>0</state>
            </seat>
            <seat id="E3">
                <state>0</state>
            </seat>
            <seat id="E4">
                <state>0</state>
            </seat>
        </seats>
    </function>
    <function id="3242">
        <date>
            <day>9</day>
            <month>06</month>
            <year>2016</year>
        </date>
        <hour>
            <hours>2</hours>
            <min>40</min>
        </hour>
        <rowCant>4</rowCant>
        <columnCant>5</columnCant>
        <seats>
            <seat id="A1">
                <state>0</state>
            </seat>
            <seat id="A2">
                <state>0</state>
            </seat>
            <seat id="A3">
                <state>0</state>
            </seat>
            <seat id="A4">
                <state>0</state>
            </seat>
            <seat id="B1">
                <state>0</state>
            </seat>
            <seat id="B2">
                <state>0</state>
            </seat>
            <seat id="B3">
                <state>0</state>
            </seat>
            <seat id="B3">
                <state>0</state>
            </seat>
            <seat id="B4">
                <state>0</state>
            </seat>
            <seat id="C1">
                <state>0</state>
            </seat>
            <seat id="C2">
                <state>0</state>
            </seat>
            <seat id="C3">
                <state>0</state>
            </seat>
            <seat id="C4">
                <state>0</state>
            </seat>
            <seat id="D1">
                <state>0</state>
            </seat>
            <seat id="D2">
                <state>0</state>
            </seat>
            <seat id="D3">
                <state>0</state>
            </seat>
            <seat id="D4">
                <state>0</state>
            </seat>
            <seat id="E1">
                <state>0</state>
            </seat>
            <seat id="E2">
                <state>0</state>
            </seat>
            <seat id="E3">
                <state>0</state>
            </seat>
            <seat id="E4">
                <state>0</state>
            </seat>
        </seats>
    </function>
     <function id="3242">
        <date>
            <day>9</day>
            <month>06</month>
            <year>2016</year>
        </date>
        <hour>
            <hours>2</hours>
            <min>40</min>
        </hour>
        <rowCant>4</rowCant>
        <columnCant>5</columnCant>
        <seats>
            <seat id="A1">
                <state>0</state>
            </seat>
            <seat id="A2">
                <state>0</state>
            </seat>
            <seat id="A3">
                <state>0</state>
            </seat>
            <seat id="A4">
                <state>0</state>
            </seat>
            <seat id="B1">
                <state>0</state>
            </seat>
            <seat id="B2">
                <state>0</state>
            </seat>
            <seat id="B3">
                <state>0</state>
            </seat>
            <seat id="B3">
                <state>0</state>
            </seat>
            <seat id="B4">
                <state>0</state>
            </seat>
            <seat id="C1">
                <state>0</state>
            </seat>
            <seat id="C2">
                <state>0</state>
            </seat>
            <seat id="C3">
                <state>0</state>
            </seat>
            <seat id="C4">
                <state>0</state>
            </seat>
            <seat id="D1">
                <state>0</state>
            </seat>
            <seat id="D2">
                <state>0</state>
            </seat>
            <seat id="D3">
                <state>0</state>
            </seat>
            <seat id="D4">
                <state>0</state>
            </seat>
            <seat id="E1">
                <state>0</state>
            </seat>
            <seat id="E2">
                <state>0</state>
            </seat>
            <seat id="E3">
                <state>0</state>
            </seat>
            <seat id="E4">
                <state>0</state>
            </seat>
        </seats>
    </function>
    <function id="41235">
        <date>
            <day>21</day>
            <month>06</month>
            <year>2016</year>
        </date>
        <hour>
            <hours>3</hours>
            <min>00</min>
        </hour>
        <rowCant>4</rowCant>
        <columnCant>5</columnCant>
        <seats>
            <seat id="A1">
                <state>0</state>
            </seat>
            <seat id="A2">
                <state>0</state>
            </seat>
            <seat id="A3">
                <state>0</state>
            </seat>
            <seat id="A4">
                <state>0</state>
            </seat>
            <seat id="B1">
                <state>0</state>
            </seat>
            <seat id="B2">
                <state>0</state>
            </seat>
            <seat id="B3">
                <state>0</state>
            </seat>
            <seat id="B3">
                <state>0</state>
            </seat>
            <seat id="B4">
                <state>0</state>
            </seat>
            <seat id="C1">
                <state>0</state>
            </seat>
            <seat id="C2">
                <state>0</state>
            </seat>
            <seat id="C3">
                <state>0</state>
            </seat>
            <seat id="C4">
                <state>0</state>
            </seat>
            <seat id="D1">
                <state>0</state>
            </seat>
            <seat id="D2">
                <state>0</state>
            </seat>
            <seat id="D3">
                <state>0</state>
            </seat>
            <seat id="D4">
